-- MySQL Script generated by MySQL Workbench
-- piektdiena, 2018. gada  8. jūnijs, plkst. 16 un 12
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`city` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cinema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cinema` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `city id` INT NOT NULL,
  `address` VARCHAR(120) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone number` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `city id_idx` (`city id` ASC),
  CONSTRAINT `city id`
    FOREIGN KEY (`city id`)
    REFERENCES `mydb`.`city` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`movie` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NOT NULL,
  `time` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`trailer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`trailer` (
  `id` INT NOT NULL,
  `movie id` INT NOT NULL,
  `youtube url` VARCHAR(2083) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `movie id_idx` (`movie id` ASC),
  CONSTRAINT `movie id`
    FOREIGN KEY (`movie id`)
    REFERENCES `mydb`.`movie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cinema movies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cinema movies` (
  `id` INT NOT NULL,
  `cinema id` INT NOT NULL,
  `movie id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `cinema id_idx` (`cinema id` ASC),
  INDEX `movie id_idx` (`movie id` ASC),
  CONSTRAINT `cinema id`
    FOREIGN KEY (`cinema id`)
    REFERENCES `mydb`.`cinema` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `movie id`
    FOREIGN KEY (`movie id`)
    REFERENCES `mydb`.`movie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hall`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`hall` (
  `id` INT NOT NULL,
  `cinema id` INT NOT NULL,
  `rows` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `cinema id_idx` (`cinema id` ASC),
  CONSTRAINT `cinema id`
    FOREIGN KEY (`cinema id`)
    REFERENCES `mydb`.`cinema` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hall seats per row`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`hall seats per row` (
  `id` INT NOT NULL,
  `hall id` INT NOT NULL,
  `row` INT NOT NULL,
  `seats per row` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `hall id_idx` (`hall id` ASC),
  CONSTRAINT `hall id`
    FOREIGN KEY (`hall id`)
    REFERENCES `mydb`.`hall` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`session` (
  `id` INT NOT NULL,
  `cinema movies id` INT NOT NULL,
  `hall id` INT NOT NULL,
  `time` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `cinema movie id_idx` (`cinema movies id` ASC),
  INDEX `hall id_idx` (`hall id` ASC),
  CONSTRAINT `cinema movie id`
    FOREIGN KEY (`cinema movies id`)
    REFERENCES `mydb`.`cinema movies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `hall id`
    FOREIGN KEY (`hall id`)
    REFERENCES `mydb`.`hall` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`price per row`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`price per row` (
  `id` INT NOT NULL,
  `session id` INT NOT NULL,
  `row` INT NOT NULL,
  `price` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `session id_idx` (`session id` ASC),
  CONSTRAINT `session id`
    FOREIGN KEY (`session id`)
    REFERENCES `mydb`.`session` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`payment system`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`payment system` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bough seats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bough seats` (
  `id` INT NOT NULL,
  `session id` INT NOT NULL,
  `payment system id` INT NOT NULL,
  `hall id` INT NOT NULL,
  `row` INT NOT NULL,
  `seat number` INT NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `order number` VARCHAR(500) NOT NULL,
  `phone number` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `payment system id_idx` (`payment system id` ASC),
  INDEX `hall id_idx` (`hall id` ASC),
  CONSTRAINT `session id`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`session` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `payment system id`
    FOREIGN KEY (`payment system id`)
    REFERENCES `mydb`.`payment system` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `hall id`
    FOREIGN KEY (`hall id`)
    REFERENCES `mydb`.`hall` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
